### ISSUE TITLE
Version without the second hand

### ISSUE THREAD

**Issue by DFelten** [soffes/Clock.saver#14]
Thanks for the beautiful screensaver. Could you maybe ad a version without the second hand?

**Comment by soffes** [comment]
<img width="801" alt="Screen Shot 2019-11-02 at 10 59 23 AM" src="https://user-images.githubusercontent.com/52870/68073652-5a965480-fd60-11e9-8032-e4a82ed1ed3d.png">

Added in version 0.6.0.
