### ISSUE TITLE
white screen bug appears. Hope to fix.

### ISSUE THREAD

**Issue by ChinaHackers** [soffes/Clock.saver#16]
Select the screen saver option and click ok. Click the screen saver option again, a white screen bug appears. Hope to fix.

**Comment by soffes** [comment]
I think this is a macOS bug with Swift screensavers. If you restart System Preferences, it goes away, right?

**Comment by ChinaHackers** [comment]
> 我认为这是Swift屏幕保护程序的macOS错误。如果重新启动系统偏好设置，它会消失，对吗？

I have submitted code to fix a white screen bug. I tested it and it was fixed!

**Comment by soffes** [comment]
@ChinaHackers I left a suggestion on your PR. Once you accept it, I can merge your PR and close this issue.

**Comment by ChinaHackers** [comment]
> @ChinaHackers I left a suggestion on your PR. Once you accept it, I can merge your PR and close this issue.

Great!
