### ISSUE TITLE
Love this screensaver- is there any way to address the consistent security pop-up preventing its launch?

### ISSUE THREAD

**Issue by jdsmeak** [soffes/Clock.saver#18]
<img width="478" alt="Screen Shot 2020-05-04 at 2 30 00 PM" src="https://user-images.githubusercontent.com/64288562/81010623-c8a4fc80-8e13-11ea-976a-bd68108ab669.png">

**Comment by soffes** [comment]
Hmm I haven't seen this before. I can make another release that's notarized and see if that fixes it 🤷

**Comment by supradijn** [comment]
Having similar issues too :(

<img width="532" alt="Screenshot 2020-05-12 at 10 02 33" src="https://user-images.githubusercontent.com/8234609/81656933-c1937500-9437-11ea-9153-5cf7f6a59d2c.png">

**Comment by soffes** [comment]
I ran out of Developer ID certificates. Requested more from Apple.

**Comment by jdsmeak** [comment]
Hi @soffes, were you able to get more certificates to solve this pesky issue? Thanks ever so much, this is an AWESOME screensaver for Mac.

**Comment by soffes** [comment]
Sorry haven't had time to look at this recently. I don't see this error on any of my computers either :/

**Comment by supradijn** [comment]
I tried once more cause I would love to use it, but it keeps giving this error once more.

<img width="532" alt="Screenshot 2020-07-18 at 14 05 56" src="https://user-images.githubusercontent.com/8234609/87852181-ff14f280-c8ff-11ea-9f02-5e8ba43b1724.png">

**Comment by meisterleise** [comment]
I don't have this issue
(macOS 14.6)

**Comment by soffes** [comment]
Going to close for now. When I make the next release, I'll work on signing stuff.
