### ISSUE TITLE
blank settings

### ISSUE THREAD

**Issue by meisterleise** [soffes/Clock.saver#20]
After I choose a clock in the options, I can't go to the options again. The area is blank. I've to quit the system settings and open it again, choose the screensaver again. Now I can change the settings. Understand? Otherwise here's a small screencast:
https://www.screencast.com/t/Ymu7fxsRsDs

clock 0.7.0
macOS 14.6

cheers meisterleise

**Comment by soffes** [comment]
So weird. Thanks for reporting.

**Comment by soffes** [comment]
Closing this since I can't reproduce. Feel free to reopen if you're still seeing this with version 0.7.1 on the latest macOS!
