### ISSUE TITLE
Changed code-signature in version 0.7.1?

### ISSUE THREAD

**Issue by suschizu** [soffes/Clock.saver#23]
Hello!
I've recieved a notification that the code signature has changed between version 0.7.0 and 0.7.1 
can you confirm this?

EXPECTED Nothing Magical Inc. (UP9C8XM22A) but FOUND Apple Development: Samuel Soffes (F5W43ET9UG)

Thanks!

**Comment by soffes** [comment]
That's expected! I closed the Nothing Magical developer account and am using my personal one now.

**Comment by suschizu** [comment]
perfect thanks for the information ;D

**Comment by core-code** [comment]
using the personal one is fine, but could you please use the "Developer ID" signature? the "Apple Development" certificate is only for uploading packages to the Mac App Store. i am expecting people will see "Gatekeeper" issues because of this.

**Comment by soffes** [comment]
@core-code oh my bad. I thought I used the Developer ID one. I'll make another release now with the correct signature.

**Comment by soffes** [comment]
@core-code here's the output for [0.7.2](https://github.com/soffes/Clock.saver/releases/tag/v0.7.2):

```
$ codesign -dv --verbose=2 /Users/soffes/Desktop/Clock.saver
Executable=/Users/soffes/Desktop/Clock.saver/Contents/MacOS/Clock
Identifier=com.samsoffes.clock
Format=bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20400 size=1239 flags=0x0(none) hashes=32+3 location=embedded
Signature size=8976
Authority=Developer ID Application: Samuel Soffes (LHDXBG4XBK)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Dec 8, 2021 at 9:57:27 AM
Info.plist entries=23
TeamIdentifier=LHDXBG4XBK
Sealed Resources version=2 rules=13 files=19
Internal requirements count=1 size=212
```

**Comment by core-code** [comment]
confirmed, looks fine, thanks!

**Comment by manutorr** [comment]
I'm still getting this gatekeeper alert and haven't been able to make it work... anything I'm doing wrong here? @soffes 

<img width="372" alt="image" src="https://user-images.githubusercontent.com/6828154/160592739-84647eca-370d-48b7-b308-f0af5203d3f8.png">
