### ISSUE TITLE
Apple cannot check for malicious software

### ISSUE THREAD

**Issue by SamuelAcunaPhD** [soffes/Clock.saver#25]
Tried installing it using latest macOS. Got an error:

`“Clock.saver” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.`

**Comment by soffes** [comment]
Can you try version 0.7.3? https://github.com/soffes/Clock.saver/releases/tag/v0.7.3

**Comment by SamuelAcunaPhD** [comment]
Awesome, thanks! It works and looks great.


From: Sam Soffes ***@***.***>
Date: Wednesday, June 7, 2023 at 8:14 PM
To: soffes/Clock.saver ***@***.***>
Cc: Samuel Acuna ***@***.***>, Author ***@***.***>
Subject: Re: [soffes/Clock.saver] Apple cannot check for malicious software (Issue #25)

Can you try version 0.7.3? https://github.com/soffes/Clock.saver/releases/tag/v0.7.3
